### ISSUE TITLE
No "phantom" data in input/ dir

### ISSUE THREAD

**Issue by SpencerXia** [gjadick/dex-ct-sim#1]
Hi Gia

I try to run your main.py, but found no phantom data there. Could you update it?

Thanks

**Comment by gjadick** [comment]
Thanks for bringing this to my attention! I'll upload an example phantom, probably a water cylinder on an air background. 

I didn't originally upload a phantom because I was using an XCAT phantom, which you can request from CVIT at Duke: [link](https://cvit.duke.edu/resource/xcat-phantom-program/) 

If you're interested, it's pretty straightforward to generate computational phantoms constructed from just cylinders, like an image quality phantom. The inputs needed are listed in the Phantom class in system.py. Once I upload an example you can see the formatting style.

**Comment by gjadick** [comment]
Just added a phantom. Does it work for you now?

**Comment by SpencerXia** [comment]
> Just added a phantom. Does it work for you now?

Thanks, it works.
